-- AlterTable
ALTER TABLE "product_snapshots" ADD COLUMN IF NOT EXISTS "description" TEXT;
ALTER TABLE "product_snapshots" ADD COLUMN IF NOT EXISTS "brand" TEXT;
ALTER TABLE "product_snapshots" ADD COLUMN IF NOT EXISTS "originalPrice" DECIMAL(12,2);
ALTER TABLE "product_snapshots" ADD COLUMN IF NOT EXISTS "reviewCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "product_snapshots" ADD COLUMN IF NOT EXISTS "videoUrls" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "product_snapshots" ADD COLUMN IF NOT EXISTS "variants" JSONB NOT NULL DEFAULT '[]';

ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "description" TEXT;
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "brand" TEXT;
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "originalPrice" DECIMAL(12,2);
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "reviewCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "videoUrls" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "variants" JSONB NOT NULL DEFAULT '[]';
